domain: hi
input_file_regex: HI/NHDPLUS_H_20*_HU4_GPKG
vpu_id: "20"
crs: EPSG:32604
permitted_fcodes:
  - 'Canal/Ditch'
  - 'Stream/River: Hydrographic Category = Perennial'
  - 'Stream/River: Hydrographic Category = Intermittent'
  - 'Artificial Path'
  - 'Pipeline: Pipeline Type = Siphon'
  - 'Pipeline: Pipeline Type = Aqueduct'
  - 'Pipeline'
  - 'Connector'
  - 'Canal Ditch: Canal Ditch Type = Stormwater'
  # These FCODES are currently disabled in HI due to incorrect NULL `toid` and `dn_hydroseq` values.
  # - 'Pipeline: Pipeline Type = Aqueduct; Relationship to Surface = At or Near'
  # - 'Pipeline: Pipeline Type = Aqueduct; Relationship to Surface = Underground'
  # - 'Pipeline: Pipeline Type = Penstock; Relationship to Surface = At or Near'
