domain: prvi
input_file_regex: PRVI/NHDPLUS_H_21*_HU4_GPKG
vpu_id: "21"
crs: EPSG:6566
permitted_fcodes:
  - 'Canal/Ditch'
  - 'Stream/River: Hydrographic Category = Perennial'
  - 'Stream/River: Hydrographic Category = Intermittent'
  - 'Artificial Path'
  - 'Pipeline: Pipeline Type = Aqueduct; Relationship to Surface = At or Near'
  - 'Pipeline: Pipeline Type = Aqueduct; Relationship to Surface = Underground'
  - 'Pipeline: Pipeline Type = Siphon'
  - 'Pipeline: Pipeline Type = Aqueduct'
  - 'Pipeline'
  - 'Connector'
  - 'Canal Ditch: Canal Ditch Type = Stormwater'
  - 'Pipeline: Pipeline Type = Penstock; Relationship to Surface = At or Near'
